### ISSUE TITLE
GMT offset question. 

### ISSUE THREAD

**Issue by mixographer** [dirkx/SMPTE-EBU-TimecodeGenerator-ESP32#4]
Not an issue, but more of a question. 

I don't understand the difference between NTP time and local time. 

So if I compile this, and change the bool of "tz" to an int and make it -8. 

I get this on the web config interface: 

NTP time: 13:15:58 (with fiddle factor of 0 already included)
Local time: 9:15:59 PM
Current GMT offset: -8 hour(s)
Observing Daylight Saving time (summer time): no

and what I would want is for the timecode to say it's 9:15 and for 9:15 to display on the clock. 

But my clock is at 13:15 which is like utc +16 for me. 

I just don't understand how to un-hard-code this CET timezone. 

-3 modulo 24 is 21 right which is 9 pm, but why is the timecode at 13:58?

Thanks

**Comment by dirkx** [comment]
The sum is:

     local_time_hour = (utc_hour + tz + (dst ? 1 : 0)) % 24; // CET summertime/DST

so unless there is something odd - I would expect utc_hour=13. (You can confirm with Serial.printf("Hours %u\n",hour).

So if you are 8 hours ahead, e..g in Asia, (offset = +8 hours); we get 13+ 8 = 21. Which is 9 PM. 

Add a % 12 if you want PM/AM or change te settings on the physical clock.

If you are in Los Gatos then your offset is -8 hours.

In that case - you get utc_hour=13; hour = 13 -8 which is 3AM in the morning.

**Comment by dirkx** [comment]
I've added some timeszone support examples to the code.

**Comment by mixographer** [comment]
The new code using the espressif timezone support is great. I added back in the wi-fi details and changed the define for 30fps. It seems like it was running at 30fps, but the web interface was reading the define and saying it was 25fps. 

Just to see how good the timecode was, I used the little device to 'jam' both a Denecke SB-T lockit box and a Denecke GR-1 timecode generator. It works great in both cases. 

I wonder if running the code off a GPS 1 pulse per second would be more accurate, but this is accurate enough and super easy to use. 

Thanks for an interesting project, and for your help with this timezone setting business.

**Comment by dirkx** [comment]
Glad to hear. Will double check the FPS settings in the code.

As to the 1PPS - it would be more accurate in theory. But the practical problem is that the RMT (the circuitry in the chip) that creatres the SMPTE signal is, AFAIK, not that perfectly under control of the software right now. You cannot quite control it frame-accurate; as the RMT runs 'on its own'. We just fill a buffer; but are not sure when exactly the head of a new buffer will go out (currently). I've tried to measure this with a scope/logic analyser; but found that things like interrupt handler (e.g. for wifi/ethernet) throw me off too far.

So I guess we would need something like a full PLL in the NTP client; and once that is done; use something in hardware to align/(re)start the RMT. So we know exactly at what time the 'head' of each buffer goes out (or we can 'trigger' this).

Because trying to slew it makes the studio clocks I have here all go unhappy / out-of-sync warning LED comes on with the slightest error.
